### ISSUE TITLE
Request for Write privileges

### ISSUE THREAD

**Issue by mimshwright** [tleunen/pixi-multistyle-text#150]
Hey @tleunen , I’d love to contribute a few PRs from myself and others, but it seems like you have a lot on your plate right now. LMK when you have some bandwidth and we can consolidate the work into this project. If you would consider adding me as a maintainer, I could take the lead on some of it. Thank you!

**Comment by tleunen** [comment]
Hey @mimshwright ! Thanks for volunteering yourself to improve the project. I invited you as a collaborator so you should get access once you accept it. I'll also add you on NPM once you give me your handle there ;)
Thanks again.

**Comment by mimshwright** [comment]
Thanks! it's mimshwright on npm too

**Comment by mimshwright** [comment]
Was about to start merging some PRs, starting with #96. I was going to do that work in a non-`master` branch (`dev`) but I'm not sure I have write access for that. It could also be my Github skills are just rusty.

**Comment by tleunen** [comment]
You should have access to create branches and do every operations in the repo. Do you get an error?

**Comment by mimshwright** [comment]
@tleunen quick update to explain why i haven't done anything with the write privileges you so quickly bestowed on me:  I went to work on the library, specifically trying to add inline sprites for a client and ran into some roadblocks that led me to reconsider / redesign how it might work. However, now I've made such significant changes to the library that it's practically a new thing at this point. When I reach a new stopping point ill most likely spin off a new release which I'll mention here. If it makes sense to the owners of this repo you can replace the original or let them live separate lives.

**Comment by mimshwright** [comment]
Update: The new library / component is called pixi-tagged-text and it can be found here: https://github.com/mimshwright/pixi-tagged-text
