### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by tleunen** [tleunen/pixi-multistyle-text#21]
It would be great to also have a test suite to make sure we don't introduce any regressions.

I'm not sure the best way to do it but one way I have in mind is that we can create snapshot of the final image it has to produce.

**Comment by bluepichu** [comment]
Not a bad idea.  I've also been thinking of beefing up the demo page, so we could probably kill two birds with one stone here.

**Comment by bluepichu** [comment]
Associated PR is #29.
