### ISSUE TITLE
Building isn't working

### ISSUE THREAD

**Issue by themoonrat** [tleunen/pixi-multistyle-text#31]
Hiya.

First of all, loving the idea on this, looks great so far :) 

Problem I've got is I can't compile the .ts! 

I get the following error

C:\Projects\WebGL\pixi-multistyle-text-themoonrat>npm run build

> pixi-multistyle-text@0.4.0 build C:\Projects\WebGL\pixi-multistyle-text-themoonrat
> tsc; browserify index.js -p tsify -s MultiStyleText -o dist/pixi-multistyle-text.js -d

error TS5023: Unknown compiler option 's'.
error TS5023: Unknown compiler option 'o'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! pixi-multistyle-text@0.4.0 build: `tsc; browserify index.js -p tsify -s MultiStyleText -o dist/pixi-multistyle-text.js -d`
npm ERR! Exit status 1

**Comment by bluepichu** [comment]
Based on the fact that `tsc` appears to be throwing errors for unknown arguments that are supposed to be passed to `browserify`, I'm going to assume this is probably a Windows issue related to the semicolon used in the build script.

I think this might be fixable by replacing the semicolon with `&&`.  Fortunately, I have a Windows machine that I can test on, so I'll take a look there.

**Comment by themoonrat** [comment]
Yeps, replacing the ; with a && worked :+1:

**Comment by bluepichu** [comment]
Great, I'll make a PR for it.

**Comment by tleunen** [comment]
PR Merged. Thanks
