### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by bluepichu** [tleunen/pixi-multistyle-text#48]
Proposed by @djmisterjon in #46.  Drawing bounding boxes, baselines, top/bottom for each line, etc. could be really helpful for debugging.

**Comment by bluepichu** [comment]
Here's what this looks like right now:

<img width="301" alt="screenshot 2017-07-16 11 30 57" src="https://user-images.githubusercontent.com/1878074/28250325-581ee3ce-6a1a-11e7-8f2a-26d6cc9f8d72.png">

There are options for global enable/disable and the colors of each of the lines.

You can also override the global value for certain styles via a new optional `debug` option.  Here, I've disabled debug mode for `default`:

<img width="536" alt="screenshot 2017-07-16 11 31 03" src="https://user-images.githubusercontent.com/1878074/28250329-7df01848-6a1a-11e7-8c88-c448110f9dbc.png">

The only other lines remaining that I currently plan to add are base/top/bottom for each line.

**Comment by bluepichu** [comment]
PR Filed: #51.

**Comment by djmisterjon** [comment]
hey awsome jobs , is look very nice!

**Comment by djmisterjon** [comment]
for the  top/baseline/bottom/bounding per-line.
I find the behavior difficult to manage align, so I just create a new proprety in pixi.style that allows to position in line.
it called :     **lineStyle**:    //'top'||'middle'||'bottom' , but your idea is greate with custom per style
```
MVPixi_Text.prototype.positioningChild = function(pixiText) {
    var data = pixiText._resultLine;
    var pixiChild = pixiText.children;
    var lS = pixiText._style.primary.lineStyle;
    var lA = pixiText._style.primary.align;
    var lH = pixiText._style.primary.lineHeight || 0;
    lS = lS==='middle'&& 0.5 || lS==='bottom'&& 1 || 0; // lineStyle
    lA = lA==='center'&& 0.5 || lA==='right'&& 1 || 0;  // lineAlign
    var limit = pixiText._style.primary.wordWrapWidth || Math.max.apply(Math, pixiText._dataLW);
    pixiText._limitLineMax = limit; // asign because alignBypicture work with limit and not
    for (var R=0, id=0, lineMaxH=0, Y=0, alignX=0, LEN=data.length; R<LEN; R++) {
        if(lA){ alignX = (limit-pixiText._dataLW[R])*lA; };
        for (var r=0, len=data[R].length; r<len; r++, id++) {
            pixiChild[id].anchor.y = lS;
            pixiChild[id].x = data[R][r]._x+alignX;
            pixiChild[id].y = Y;
        };
        Y+=pixiText._dataLH[R]+lH;
    };
return pixiText
};
```

**Comment by djmisterjon** [comment]
I do not know why these now, but I am much fun to code and make debugger for my work.
Here is another, an extension with pixi debug, it is compatible, and allows to position the parent sprite container in the node js app interface.
see on youtube =>>
<a href="http://www.youtube.com/watch?feature=player_embedded&v=iIAX-NIPlxo
" target="_blank"><img src="http://img.youtube.com/vi/iIAX-NIPlxo/0.jpg" 
alt="youtube debug" width="240" height="200" border="20" /></a>
