### ISSUE TITLE
Line height

### ISSUE THREAD

**Issue by nmiguelmoura** [tleunen/pixi-multistyle-text#49]
Hi,
First let me thank you for make this available, its very usefull and easy to use.
While using MultistyleText, I noticed I'm not able to control lineHeight. Is this a known issue? I'm using PIXI v.4.5.1.
Thanks,
Nuno

**Comment by bluepichu** [comment]
So there's [_supposed_ to be](http://pixijs.download/release/docs/PIXI.TextStyle.html) a `lineHeight` property that you can add to any text style, but it doesn't seem to actually be applied anywhere in our code.

Actually, that style doesn't seem to be used anywhere in `PIXI.Text` either, even though it's listed in the documentation...

Implementing this shouldn't be too bad, though I'll have to think about how it plays with multiple font sizes and vertical alignments.  (I'll probably just look into what CSS does and follow that as a guide.)

**Comment by bluepichu** [comment]
...though we'll also need to decide which units to use.  I'd personally probably opt for a multiplier (CSS's unitless option), though interpreting it as a number of pixels (like CSS's length option) is also a reasonable choice.

**Comment by nmiguelmoura** [comment]
Hi,
Thank you.
I understand that, but in PIXI.Text, lineHeight works just fine.
The only thing for now that is preventing me from using MultiText for all my text fields in PIXI is this lineHeight property. Once its working, i'll make it my default text in my apps, because its great and solves me a lot of problems.
Congrats,
Nuno

**Comment by bluepichu** [comment]
Ah - apologies.  I think I accidentally tested with a crazy-out-of-date copy of Pixi.

Looks like they use the equivalent of CSS's length option.  That shouldn't be too hard to fold in; I'll try to include that with the new vertical align options.

**Comment by kuoruan** [comment]
```lineHeight``` still not work. 😢

**Comment by bluepichu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [`lineHeight` does not work](https://trello.com/c/nVQHWfoB/1-lineheight-does-not-work)

**Comment by EloB** [comment]
I tried to solve `lineHeight` and it worked for me but I'm not sure about vertical align. I don't use that. Can someone test it?

**Comment by tleunen** [comment]
@bluepichu - Would you have time to check out the suggested PR #71 ?

**Comment by andrew-ntk** [comment]
Will this bug be fixed in the near future?
