### ISSUE TITLE
lineWidth value is wrong when using a stroke

### ISSUE THREAD

**Issue by Owlzy** [tleunen/pixi-multistyle-text#59]
Using PIXI 4.5.6, when you use a stroke of any size and any alignment the text gets cut off.

I added some hacky stuff below which has fixed the issue for me.

`        
                var foo = Object.keys(textStyles).map(function (key) { return textStyles[key]; });
                var myValue;
                var bar = foo.reduce(function (prev, cur) {
                    myValue = cur.strokeThickness;
                    return Math.max(prev, cur.strokeThickness || 0);
                }, 0);
                lineWidth += myValue * 8;// hacky fix for cut off text when using a stroke (I think 8 is stroke width)
                lineWidths[i] = lineWidth;
`

This is where the lines are looped through and the lineWidths calculated.  I found the value 8 by trial and error but this is also the width of stroke I used, so I'm guessing that's what this value is.

**Comment by bluepichu** [comment]
Thanks for the report!  Looks like this is an obvious failing example:

```ts
let text = new MultiStyleText("Let's make some <ml>multiline</ml>\nand <ms>multistyle</ms> text for\n<pixi>Pixi.js!</pixi>",
{
	"default": {
		fontFamily: "Arial",
		fontSize: "24px",
		fill: "#cccccc",
		align: "center",
		strokeThickness: 100 // <-----
	},
	"ml": {
		fontStyle: "italic",
		fill: "#ff8888"
	},
	"ms": {
		fontStyle: "italic",
		fill: "#4488ff"
	},
	"pixi": {
		fontSize: "64px",
		fill: "#efefef"
	}
});
```

<img width="490" alt="screenshot 2018-01-17 13 23 02" src="https://user-images.githubusercontent.com/1878074/35059558-9095dbd0-fb89-11e7-85ef-591f0b88fb05.png">

**Comment by bluepichu** [comment]
Sorry it took me so long to get back to this!  I wasn't very sure of whether or not the fix worked when I wrote it way back in January -- revisiting it, it seems to work fine.  If you need it before #65 is merged you can pull the branch and build it locally:

```
git clone https://github.com/bluepichu/pixi-multistyle-text.git
cd pixi-multistyle-text
git checkout iss59
npm install
npm run demo
```

(The built copy will be in `<working path>/pixi-multistyle-text/dist/pixi-multistyle-test.js`.)

**Comment by bluepichu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[PMT-xx] lineWidth value is wrong when using a stroke](https://trello.com/c/r1UTlUjB/3-pmt-xx-linewidth-value-is-wrong-when-using-a-stroke)
