### ISSUE TITLE
Demo broken, dist missing, build instructions?

### ISSUE THREAD

**Issue by patrickfabrizius** [tleunen/pixi-multistyle-text#61]
Demo doesn't work, refers to ../dist which does not exist, and I can't find any build instructions?

**Comment by patrickfabrizius** [comment]
Maybe it's obvious, I figured it out, but I think instructions would be helpful :) #62

**Comment by tleunen** [comment]
`npm run demo` is the right command.

But thanks, I'll take some time this weekend to review a bit what we have here and make sure the readme is correct as well.
