### ISSUE TITLE
Gradient fill height calculated incorrectly

### ISSUE THREAD

**Issue by martinAnsty** [tleunen/pixi-multistyle-text#64]
When using gradient fills for tags in multistyle-text the gradient is drawn based on the dimensions of the whole text object, not the dimensions of the tagged text the gradient is being applied to.

A visual example: https://codepen.io/martinAnsty/pen/errVXe

The gradient fill is actually calculated using [PIXI.Text's `_generateFillStyle()`](https://github.com/pixijs/pixi.js/blob/dev/src/core/text/Text.js#L433). If you dig through that method you can see PIXI specifically handles multiline gradient text by repeating the gradient so that it appears to be applied to each line individually.

In the case of pixi-multistyle-text I think `_generateTextStyle()` needs reimplementing to calculate the dimensions of the text first rather than simply using `canvas.width` and `canvas.height`.

**Comment by bluepichu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gradient fill height calculated incorrectly](https://trello.com/c/NMASkvd5/5-gradient-fill-height-calculated-incorrectly)

**Comment by andrew-ntk** [comment]
Hi, I am having the same issue. Is there a way to fix it?
