### ISSUE TITLE
wordWrap + letterSpacing is broken

### ISSUE THREAD

**Issue by tconkling** [tleunen/pixi-multistyle-text#67]
Using `letterSpacing` while `wordWrap=true` causes incorrect cropping. Specifically, it looks like wordWrap doesn't take a custom letterSpacing into account when deciding where to insert linebreaks, and how large the resultant texture should be.

```typescript
const str = "This is a game where you become an RNA scientist. " +
    "By solving puzzles, you will build a virtual lab.  " +
    "Then you will help invent new RNA molecules to combat " +
    "infectious diseases like tuberculosis.  Ready?";

this._text = new MultiStyleText(str, {
    "default": {
        fontFamily: "Arial",
        fontSize: 13,
        fill: 0xC0DCE7,
        wordWrap: true,
        wordWrapWidth: 185,
        letterSpacing: 5,
    }
});
```
Results in:

![screen shot 2018-07-31 at 5 14 54 pm](https://user-images.githubusercontent.com/709022/43493969-5358c82c-94e5-11e8-8d6e-475ba1f82c3c.png)

The same MultiStyleText, but with letterSpacing unset, is correctly uncropped:

![screen shot 2018-07-31 at 5 13 39 pm](https://user-images.githubusercontent.com/709022/43493911-1a3d982e-94e5-11e8-9072-98a4fc976038.png)

**Comment by bluepichu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [wordWrap and letter spacing are broken](https://trello.com/c/HcGGUXSb/6-wordwrap-and-letter-spacing-are-broken)

**Comment by andrew-ntk** [comment]
Hi, I am having the same issue. Is there a way to fix it?

**Comment by rizen** [comment]
I've fixed this issue in my custom fork fo this library. The author no longer seems responsive so I'm trying to modernize it a bit, fix bugs, and add some features. Here's the patch if you wish to try to apply it yourself. https://github.com/plainblack/pixi-multistyle-text/commit/f287e57b8c4db30d07482e70e17b893878ff6344

Or here's my version of the library if you're so inclined: https://github.com/plainblack/pixi-multistyle-text
