### ISSUE TITLE
Unable to update wordWrapWidth

### ISSUE THREAD

**Issue by pimdewit** [tleunen/pixi-multistyle-text#68]
It seems you are not able to update the wordWrapWidth property after initialisation.

```
const textNode = new MultistyleText('Lorem Ipsum', {
  default: {
    wordWrap: true,
    breakWords: true,
    wordWrapWidth: 1000
  }
});
```

Above works as expected. But once you try to change the styles afterwards

`textNode.textStyles.default.fontSize = 100;` works as expected.
`textNode.textStyles.default.wordWrapWidth = 100;` does not seem to do anything.

**Comment by pimdewit** [comment]
Currently managed to get around it by accessing the property through PIXI.Text's private members: `textNode._style._wordWrapWidth = width;`

**Comment by menscrem** [comment]
You can try usage `setTagStyle`
[More info](https://github.com/tleunen/pixi-multistyle-text/pull/35)

**Comment by bluepichu** [comment]
@menscrem is correct; that is the intended method of updating styling.

You can also
