### ISSUE TITLE
text displays mulitstyle properly, but html tag still shows

### ISSUE THREAD

**Issue by heaversm** [tleunen/pixi-multistyle-text#7]
Hi - I'm using pixi multistyle and it seems to be working, but the `<html>` tags I'm using seem to be rendering as well instead of being removed. This is my implementation:

```
            //Font Variables
            Constants.FONT_SHOE_DESCRIPTION: 'Adobe Heiti Std R Bold', //The font family to use for shoe descriptions beneath shoe
            Constants.FONT_SHOE_DESCRIPTION_2: 'Flama Basic', //if there is a nested font for the shoe description, it should render in this font family

multiText = "<flama>“LOREM”</flama> Ipsum

var text = new PIXI.MultiStyleText(multiText.trim(), {
                def : {
                    align: 'center',
                    font: scaled(this.fontSize) + 'px ' + Constants.FONT_SHOE_DESCRIPTION,
                    fill : Colors.HEX_BLACK
                },
                flama : {
                    align: 'center',
                    font: scaled(this.fontSize) + 'px ' + Constants.FONT_SHOE_DESCRIPTION_2,
                    fill : Colors.HEX_BLACK
                }
            });

```

and the text is rendered out as:

<img width="461" alt="screen shot 2016-12-19 at 11 13 20 am" src="https://cloud.githubusercontent.com/assets/520541/21325644/3258c96c-c5dc-11e6-970c-513de812a376.png">

where `<FLAMA></FLAMA>` tags should not be visible

**Comment by bluepichu** [comment]
As best I can tell, the issue is that you defined the tag in lower case (`flama`) but referenced it in upper case (`FLAMA`).  Tags in this library are case-sensitive, so `<flama>` and `<FLAMA>` are different tags.

If that doesn't fix your problem, could you provide more code related to the problem?  I was unable to reproduce it with what you gave above.

**Comment by bluepichu** [comment]
@heaversm, are you still having this issue?

**Comment by heaversm** [comment]
Ah,  sorry,  forgot to write back.  You were correct.  Upper case fixed
it.  I was converting to upper case in js,  but I needed to modify the case
in the data file directly.  You can close.

**Comment by bluepichu** [comment]
Great, glad it worked out.
