### ISSUE TITLE
A feature request, textOverflow with ellipsis

### ISSUE THREAD

**Issue by EloB** [tleunen/pixi-multistyle-text#70]
First I would like to thank you for this beautiful library!

Do you think it's possible to add something like `textOverflow`? It would be awesome! 😄

**Comment by tleunen** [comment]
What do you think of this @bluepichu? I like the idea. Especially for the `ellipsis` option.
I guess we could support `clip` and `ellipsis`?
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow
