### ISSUE TITLE
Incorrect formatting when using breakWords.

### ISSUE THREAD

**Issue by jwsmithgit** [tleunen/pixi-multistyle-text#74]
All spaces are removed from a string that only exists on one line (partWidth less than the wordWrapWidth) but uses breakWords.

**Comment by soylomass** [comment]
Was going to post this, it seems related to this part:
`} else if(this._style.breakWords) {
              result += words[k];
              spaceLeft -= wordWidth;
            } else {`

It's not adding the space again after adding the word.

**Comment by soylomass** [comment]
You can fix it changing the above code with:

```
} else if(this._style.breakWords) {
  result += words[k];
  spaceLeft -= wordWidth;
  if(k < words.length-1){
  result += ' ';
  spaceLeft -= this.context.measureText(" ").width;
} else {
```

**Comment by jwsmithgit** [comment]
Thanks, I edited in that fix locally too. I also believe the break words implementation doesn't work as it should?
It breaks a word without trying to fit it onto a new line first. If a part is wider than the space left, it should go to a new line. Then, if its longer than the word wrap width, it should be broken up on that new line to another new line.

**Comment by andrew-ntk** [comment]
Hi, I am having the same issue. Is there a way to fix it?
