### ISSUE TITLE
demo no longer works

### ISSUE THREAD

**Issue by blurymind** [tleunen/pixi-multistyle-text#81]
npm run demo  --> 'open' is not recognized as an internal or external command,
npm run build and open index.html in your browser -> multistyletext is undefined

**Comment by blurymind** [comment]
submitted a pr

**Comment by tleunen** [comment]
hmm... `open` might be specific to some OS.

I just tried `npm run build` and opening the demo page in my browser and everything works fine.
What browser are you using?

**Comment by blurymind** [comment]
Chrome and chromium, on Linux and windows 10

**Comment by mimshwright** [comment]
I'm pretty sure open only works on Mac

**Comment by mimshwright** [comment]
Added a check for undefined `setRealSize()` which seems to fix it for me. Also added `opener` package for cross-platform open.
