### ISSUE TITLE
Do you plan to make it compatible with Pixi 5?

### ISSUE THREAD

**Issue by soylomass** [tleunen/pixi-multistyle-text#83]
I'm migrating my project and wanted to know if it's planned.

**Comment by tleunen** [comment]
Not me personally because I don't use PIXI anymore, but I'm open to PR (or new maintainer if someone is willing to take the lead).

**Comment by blurymind** [comment]
When gdevelop gets upgraded to pixi5, I will do a PR to update this library too :)
