### ISSUE TITLE
Cannot set property realWidth

### ISSUE THREAD

**Issue by gpaluk** [tleunen/pixi-multistyle-text#84]
There seems to be an issue with the 5.0.0+ versions of PIXI and pixi-multistyle-text. I'm using TypeScript and webpack in my project but I don't think that this is related, however when attempting to use pixi-multistyle-text I receive the following error:

<img width="1486" alt="Screenshot 2019-11-26 at 08 48 39" src="https://user-images.githubusercontent.com/1716106/69613508-92c04880-1029-11ea-989f-3f0efd15b10e.png">

**Comment by tleunen** [comment]
Would you have any repro steps or even a small project hosted on codesandbox for example we could look at?

@blurymind - this might be related to your changes?

**Comment by blurymind** [comment]
hmm, hard to say without an example project. A codepen will really help here. I don't think its due to my changes, but perhaps you could give us some more information?
Does it fail in import or during render?

**Comment by gpaluk** [comment]
Hi @blurymind - Yeah, it seems to be introduced by v5. Is there a timeline for v5+ support? It seems like this might be be caused by a protected property in pixi. Starting up a basic project containing the latest pixi library and pixi-multistyle-text results in the error being displayed during render.

**Comment by blurymind** [comment]
I wonder if we can add the support without breaking 4 support. I am not
sure when gdevelop will upgrade to pixi4

**Comment by tleunen** [comment]
It would be best to support both if we can, yes.

**Comment by gpaluk** [comment]
Any updates about this? Thanks

**Comment by tleunen** [comment]
Support for Pixi 5 has been added from this plugin v0.9
